### ISSUE TITLE
How to keep special character when create dir with Storage-Access-Framework？

### ISSUE THREAD

**Issue by lzxshare** [K1rakishou/Fuck-Storage-Access-Framework#33] opened 2022-08-11 08:22 UTC
i want to create some directories  use ExternalFileManager ，some of directories  contains  space character,i want to keep these space in folder path, may you give me some useful ideas? Is it possible use URLEncoder.encode(s,s) to encode or decode segments name to deal with space character?

**Comment by K1rakishou** [comment] 2022-08-15 09:21
Initially I implemented it this way because there were some weird crashes that I couldn't fix but now I realize that those crashes were most likely caused by threading issues which were fixed months ago. So now I decided to add BadPathSymbolResolutionStrategy.Ignore which won't modify the directory/file names.

**Comment by K1rakishou** [comment] 2022-08-15 09:32
Released in v1.1.3

**Comment by lzxshare** [comment] 2022-08-15 09:40
> 版本号 v1.1.3

thank you very much!  I modified your source code and implemented it by myself.here is my solution ：
![image](https://user-images.githubusercontent.com/39763177/184612956-c9511e3b-0a26-4e4c-a76e-f76f1fc7a4b2.png)
![image](https://user-images.githubusercontent.com/39763177/184613056-4f265f5a-6239-4b41-b7aa-89e618885b57.png)
In fact, some illegal characters in the file path, like " "+ % & ... and so on,these illegal characters should be  processed

**Comment by K1rakishou** [comment] 2022-08-15 10:11
Oh I see, I guess that makes sense. Thanks, I will implement something like that as well.

**Comment by lzxshare** [comment] 2022-08-15 11:08
> 哦，我明白了，我想这是有道理的。谢谢，我也会实现这样的东西。

oh,I forgot, it's a really great library that solves a lot of problems on Storage-Access-Framework ，and design is also amazing, thanks for your open source

**Comment by lzxshare** [comment] 2022-08-15 11:12
> Oh I see, I guess that makes sense. Thanks, I will implement something like that as well.

oh,i forget, this is a wonderful library，it solves so many problem on Storage-Access-Framework ，and it has very reasonable design. thanks for your open source

**Comment by lzxshare** [comment] 2022-08-15 12:13
solved

**Closed as completed** 2022-08-15 12:13 UTC
